# Google Cloud Run configuration
runtime: python311

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# For App Engine Standard Python 3, use Python entrypoint
# The PORT environment variable will be automatically set by App Engine
entrypoint: python main.py

